### ISSUE TITLE
Missing forward/rewind buttons in the console

### ISSUE THREAD

**Issue by hbenl** [replayio/devtools#7108]
See https://discord.com/channels/779097926135054346/984197127565627422
Here are 2 recordings of the same e2e test (with the same underlying example recording and the same devtools preview deploy):
https://app.replay.io/recording/1cd332cc-7bd5-43a7-90ed-b48a18a7ecf8 - this one was made in CI, where the test failed
https://app.replay.io/recording/3db5ca49-de5e-4488-82bc-32e2f8787aeb - this one was made manually, here the test succeeds
Note that you can't *see* that the buttons are missing because this is an e2e test recording. I was unable to reproduce the missing buttons while recording.
The recordings contain comments explaining what went wrong in the first recording and how it works in the second.

**Comment by hbenl** [comment]
This was introduced in #7064

**Comment by bvaughn** [comment]
Thanks for tracking the regression down Holger. I'll take a look.

**Comment by bvaughn** [comment]
I'm not sure I understand the comments you left on that recording, @hbenl. I left some replies.

**Comment by bvaughn** [comment]
I feel kind of stupid at the moment but I can't actually seem to run that test locally.

```sh
npm run test-e2e breakpoints-02  # This runs
npm run test-e2e node_console-02 # This doesn't run
```

It fails with:
```sh
 FAIL  test/e2e/tests/node_console-02.test.ts
  ✕ uncaught exceptions should show up. (5 ms)

  ● uncaught exceptions should show up.

    expect(received).toBeTruthy()

    Received: undefined

      24 |     throw e;
      25 |   }
    > 26 |   expect(exampleRecordingId).toBeTruthy();
         |                              ^
      27 |
      28 |   const testUrl = `${config.devtoolsUrl}/recording/${exampleRecordingId}?test=${script}`;
      29 |   console.log("Recording test:", testUrl);

      at toBeTruthy (test/e2e/runTest.ts:26:30)
      at Object.<anonymous> (test/e2e/tests/node_console-02.test.ts:4:3)
```

They're both e2e tests right? Why does one work and the other fail.

**Comment by bvaughn** [comment]
Sleuthing update.

This early return is related to the problem, but I don't think it was the _cause_. It's just easier to trigger the case now because of Global Loader 1.6:
https://github.com/replayio/devtools/blob/6acf72e0230d4aff22421cf8d1b7c426614f663c/src/devtools/client/debugger/src/actions/pause/paused.js#L65-L69

We early return because if we don't, the Thunk will go on to create a pause:
https://github.com/replayio/devtools/blob/6acf72e0230d4aff22421cf8d1b7c426614f663c/src/devtools/client/debugger/src/actions/pause/paused.js#L77-L79

Which will try to run a command that will fail:
https://github.com/replayio/devtools/blob/6acf72e0230d4aff22421cf8d1b7c426614f663c/packages/protocol/thread/pause.ts#L145

Stepping back out. Why does this matter? How is it related?

It's related because the part of the web console that renders the fast-forward/rewind buttons _also_ early returns if there isn't a paused point:
https://github.com/replayio/devtools/blob/6acf72e0230d4aff22421cf8d1b7c426614f663c/src/devtools/client/webconsole/components/Output/Message.js#L163-L178

Literally the only reason though is because that code wants to know whether to show "fast-forward" or "rewind":
https://github.com/replayio/devtools/blob/6acf72e0230d4aff22421cf8d1b7c426614f663c/src/devtools/client/webconsole/components/Output/Message.js#L210-L215

So I propose the easiest _short term_ fix is to just default to showing one or the other if we don't know for sure.

_On top of that_ I think we might want to consider doing a few follow up things:
* Update the "PAUSED" Redux action to make the Pause `id` optional. (Conceptually, you can still pause at a point _even if it's outside of a loaded region_.)
* Potentially update the `Output/Message` component to use some other value instead (like `state.app.currentPoint`?) for its label comparison. (I don't know if this is conceptually something different in some cases though so I don't want to make the change too hastily).
* Audi the fact that we have so many bits of separate state that have redundant values (e.g. `state.app.currentPoint`, `state.messages.pausedExecutionPoint`, and `state.pause.executionPoint`– also `state.messages.pausedExecutionPointTime`, `state.timeline.currentTime`). Why are these different? Can we get rid of all but one (source of truth)?
* Audit the various places subscribing to `ThreadFront.on("paused")` to update their state and see if there's a better way to handle them.
